### ISSUE TITLE
기여 방법 문서 (Contribution.md?) 필요

### ISSUE THREAD

**Issue by phg98** [hacktoberfestkorea/hacktoberfestkorea#11]
**문제점**
기여방법 문서가 없어서 기여자들이 혼란스럽겠다

**개선방안**
기여방법 문서를 알기쉽게 만들어서 추가하자.
그런데, 그러려면 작업 플로우를 정해야 하므로 제안해 주시면 논의하면서 만들고 싶습니다.

**Comment by AkiaCode** [comment]
![image](https://user-images.githubusercontent.com/71239005/97078870-45c66700-162a-11eb-8d55-ff382660a08d.png)

맨 처음 부분에는 이걸 먼저 해보는 건 어떤가요?

**Comment by phg98** [comment]
한번 초안을 만들어서 PR주시면 리뷰해볼께요 ^^

**Comment by soulee-dev** [comment]
생각보다 외국인 참여자분들도 있으셔서, 영어로 된 가이드도 작성하면 좋을거 같습니다!

**Comment by soulee-dev** [comment]
@Hritikraj8804
Thank you for contributing #222
As we are operating Hacktoberfest for Korean users, I think Contribution guide also have Korean one.
I will edit your PR to add Korean one and merge it.
