### ISSUE TITLE
Cloudflare Pages 도입

### ISSUE THREAD

**Issue by soulee-dev** [hacktoberfestkorea/hacktoberfestkorea#186]
**문제점**
매년 지난 년도 사이트를 백업하고, 올해의 사이트를 작성하기 위해 새로운 레포지토리를 생성하는것은 품이 많이 듭니다.

**개선방안**
Cloudflare Pages를 사용하면 브랜치별로 Preview 웹 사이트를 자동으로 생성해줍니다.
2022년도 페이지를 백업하기 위해서 2022 브랜치를 생성하면 자동으로 **2022.hacktoberfestkorea.com** 사이트를 생성해 줍니다.

가격은 500 빌드까지 무료이며, 이 캐파는 저희 레포지토리의 커밋수를 생각하면 충분하다고 생각 합니다.

속도는 Cloudflare의 한국 CDN을 사용하여 Github Pages를 사용하는 것 보다 훨씬 빠릅니다.

**Comment by soulee-dev** [comment]
예시 웹사이트
https://master.hacktoberfestkorea.pages.dev/ (앞에 master는 일부러 붙였습니다)

**Comment by phg98** [comment]
네 좋아보입니다. 제가 할게있다면 알려주세요

**Comment by soulee-dev** [comment]
좋은 의견 주셔서 감사합니다. 처음에는 복잡하지만, 한번 설정해 놓으면 더이상 손대지 않아도 됩니다!
몇가지 설정만 진행해주시면 제가 직접 Cloudflare Pages에 바로 붙여보도록 하겠습니다
이 아이디어를 실현하기 위해 아래와 같은 과정이 필요합니다.

형근님께 부탁드리는 부분:
- Hacktoberfest Github Organization 생성 및 Hacktoberfestt Korea을 Organization으로 소유권 이전
- 저에 대한 Organization 참여 권한 추가
  - 저 또한 Maintainer로 등록 되어있지만, 권한이 제한되어 Pages 등록등 어려움이 있습니다.
- 도메인 DNS 정보 변경
  - Github Pages에서 Cloudflare Pages로 변경되어 CNAME 을 재 등록 해야 합니다.
  
 제가 진행할 부분:
 - Hacktoberfest Korea의 Cloudflare 공용 계정 생성 및 형근님 권한 등록
 - Cloudflare Pages를 현재 페이지에 맞게 설정
 - 과거 페이지 백업 및 2023 페이지 생성

**Comment by phg98** [comment]
- [x] Hacktoberfest Github Organization 생성 및 Hacktoberfestt Korea을 Organization으로 소유권 이전
- [x] 저에 대한 Organization 참여 권한 추가
- [ ] 도메인 DNS 정보 변경 => **변경할 CNAME을 알려주세요**

**Comment by soulee-dev** [comment]
감사합니다 형근님 확인 하였습니다!
세부 정보는 Messenger로 다시 전달 드리겠습니다.
