### ISSUE TITLE
2023년 내용에 맞게 업데이트하자

### ISSUE THREAD

**Issue by phg98** [hacktoberfestkorea/hacktoberfestkorea#191]
**문제점**
2022년 내용이다

**개선방안**
2023년 내용으로 업데이트하자.

**Comment by soulee-dev** [comment]
오늘내로 빠르게 가안 작성해서 올려드리도록 하겠습니다

**Comment by soulee-dev** [comment]
@phg98 `2023-test` branch에 커밋 해놓았습니다.
테스트 웹사이트: [2023-test.hacktoberfestkorea-3fk.pages.dev](https://2023-test.hacktoberfestkorea-3fk.pages.dev/)

**Comment by soulee-dev** [comment]
#194 지적해주신 부분에 대해 수정 했습니다!

**Comment by soulee-dev** [comment]
괜찮으시다면 오늘내로 master 브랜치로 머지 하겠습니다!
그리고 원래 Cloudflare Pages 기능중 PR마다 Preview를 만들어주는 기능이 있는데, 이를 테스트 하기 위해 몇 커밋 넣었는데 잘 작동하지 않아서, 이 부분 삭제하겠습니다.

**Comment by soulee-dev** [comment]
@phg98 셀프 리뷰 진행 후, 정상적으로 배포 완료 되었습니다.

**Comment by phg98** [comment]
브라우저가 다크모드아닌 화이트모드?라이트모드? 인데 스폰서그림이 안보이네요
![image](https://github.com/hacktoberfestkorea/hacktoberfestkorea/assets/12092302/a1dc55de-dba5-41c6-adec-9c7584c34373)

**Comment by soulee-dev** [comment]
아마 기존 웹사이트에 캐시가 남아서 그런것 같습니다! 컨트롤+F5 누르시면 해결 될것 같습니다. 다른 유저들은 캐시의 TTL이 지나면 해결 될것 같습니다.

**Comment by phg98** [comment]
앗 그렇네요! ㅎㅎㅎ
