### ISSUE TITLE
영상 가운데 정렬이 필요합니다

### ISSUE THREAD

**Issue by soulee-dev** [hacktoberfestkorea/hacktoberfestkorea#218]
**문제점**
추가한 영상이 가운데 있지 않아, 보기 불편합니다.

**개선방안**
2020년 코드를 참고로 갖고왔습니다!
```
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; height: auto; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://www.youtube.com/embed/b_0rjUNK5zY' frameborder='0' allowfullscreen></iframe></div>
```

**Comment by Pariharx7** [comment]
이 문제는 내가 해결할 수 있어요. 이 문제를 나에게 할당할 수 있나요?

English:
Hey, i can fix this issue. 
Can you assign me this issue.

**Comment by soulee-dev** [comment]
@Pariharx7 Looking good, What we're trying to do it align introduction video in center.
I assigned you in this Issue!

**Comment by Pariharx7** [comment]
Sure. 
I'll fork the repo and understand the structure and then start working on it

**Comment by Pariharx7** [comment]
Sir, I forked the repository and opened it on my local machine but it is not working as base.html is not present in repository structure

**Comment by soulee-dev** [comment]
@Pariharx7 We use material docs to build website.
So, to change website html, you can edit directly in `docs/index.md`.
I hope this resolve your problem.

**Comment by Pariharx7** [comment]
I understood 

But do I need make changes inline in `docs/index.md` file or there is some stylesheet linked to it.

**Comment by phg98** [comment]
Hi, please check https://github.com/hacktoberfestkorea/hacktoberfestkorea/blob/master/docs/build.md
The file is in Korean.

**Comment by Pariharx7** [comment]
Thanks ❤

**Comment by soulee-dev** [comment]
PR: #221
